#!/bin/sh
#
# This is the default configuration file for Nopassword

server_name="example.com" # not used outside this file

# The interface and port to contact the Nopassword server
listen="127.0.0.1:1500"

# How many minutes an email login link is valid
email_expiry_time=60

# How many emails can be sent to one address per timeframe
email_tries=3
email_timeframe= 720 # minutes

# How many login requests can be made by one IP address per timeframe
ip_tries=10
ip_timeframe=1440 # minutes

# The page to redirect to after the email was sent successfully.
email_succeeded="http://$server_name/nopassword/sent.html"

# The page to redirect when there was an error sending the email.
email_failed="http://$server_name/nopassword/not_sent.html"

# The page to redirect to after the user's login link has been validated. 
login_succeeded="http://$server_name/"

# The page to redirect to if the user's login link could not be verified. 
login_failed="http://$server_name/nopassword/login_failed.html"

email_sendmail="/usr/sbin/sendmail -t -i"
email_reply_to="support@$server_name"
email_subject="Login link for $server_name"
email_body="Dear user,

Please click the following link to log into $server_name:
http://$server_name/login/{{login_token}}

To prevent anyone else from using this link, it can only be used once and
will expire after $email_expiry_time minutes.

Greetings,
The $server_name team.
"
